### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mchiriboga** [UBC-MDS/DSCI_522_Car_Insurance_Analysis#5]
@phuntsoktseten I created a new [pull request](https://github.com/UBC-MDS/DSCI_522_Car_Insurance_Analysis/pull/4) to update the README, and I assigned you as the reviewer.

**Comment by phuntsoktseten** [comment]
I received your pull request and I have reviewed the updated README and also wrote down my comments. Please check them. Thanks
